import "./globals.css"

import { Navbar } from "@/Components/navbar/navbar";

import type { WindowProvider } from '@wagmi/connectors'
import { config } from "@/Constants/config";
import { WagmiConfig } from "wagmi";

import { ToastContainer } from "react-toastify";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <WagmiConfig config={config}>
          <ToastContainer />
          <Navbar />
          {children}
        </WagmiConfig>
      </body>
    </html>
  )
}
